### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ChrisPrefect** [Sickboy78/ioBroker.sureflap#24]
The adapter uses massive amounts of ram after a few days of running.

![surepet](https://user-images.githubusercontent.com/3579863/158808794-37ffaad5-c63e-4be8-9326-451cc9a45a29.PNG)

Which leads to memory exhaustion:

![ram](https://user-images.githubusercontent.com/3579863/158808846-aa6c2363-a442-4978-83eb-850e9fec3a1d.PNG)

Adapter-Version v1.0.0
js-controller: 4.0.19

![image](https://user-images.githubusercontent.com/3579863/158809046-8030e772-cf4a-437e-aaf6-799a5511104b.png)

**Comment by Sickboy78** [comment]
Hi @ChrisPrefect ,

that is not this adapter. This adapter is called "sureflap".
You are using "surepetcareio", which is deprecated and afaik no longer in development.
I recommend to switch to my "sureflap" adapter.

Best regards

**Comment by ChrisPrefect** [comment]
Oh! I did not realize that there are two adapters for surepet! The other adapter was recently updated to 1.0 :-) I will try sureflap. Thanks!

**Comment by Sickboy78** [comment]
The original surepetcare Adapter is from https://github.com/kgerlich/iobroker.surepetcareio, where the last commit was 2019.
There are some forks including mine: https://github.com/Sickboy78/iobroker.surepetcareio where I continued development, but ultimately I decided to start from scratch with this adapter, since the old adapter was buggy and didn't meet the official requirements for iobroker adapter. Don't know, which fork you are using?!
