### ISSUE TITLE
 Feature Request: Which animal used which flap

### ISSUE THREAD

**Issue by mharms1** [Sickboy78/ioBroker.sureflap#35]
Hi,
I use 2 cat flaps and I would like to determine which cat went through which flap.
Unfortunately, I could not find any datapoint for this.

**Comment by Sickboy78** [comment]
Hi,

currently there are no dedicated data points for this, as the app also does not show this information.

But the information could be extracted from the history.
A history entry of type 0 is a movement at or through a flap.
The pet can be found in the event at pets.0.name.
The movement direction can be found in the event at movements.0.direction.
The flap can be found in the event at devices.0.name.
The time of the event can be found in the event at created_at.

I can put this on my feature list, but it will take some time.

Note however that the history API has a caching bug (not my adapter, but the API of surepetcare).
It will cache the history for 1 hour, so the history will only update every hour.

Best regards

**Comment by mharms1** [comment]
Dear Sebastian,
yes, you are right, it's only in the history and I get a push message. Its enough to cache the history for one hour. I can save the changes by myself in the database. Glad to hear you will implement this feature 👍

**Comment by MAR-L3Y** [comment]
we got 2 cat Flaps as well in our household - but in our case it gets a little more complicated: We bought a second Petdoor because our cats got used to that big flap of the first one but there is no dualscan function coming with the pet doors. We bought  and put it into the entrancedoor of the room where the Flap to the outside is in (Gateroom), but we mounted it in flipped. (with this we're able to select who's is allowed to go out and who's not by deactivating a cat for the Entranceflap of our Gateroom ) 
This is where our Problem comes in: The Status of our three cats in the app is now worthless because if a cat is coming from the outside the  status changes to inside -  the cat passes the other flap( the flipped mounted one) the status changes to outside again.
I already talked to the customersupport: my idea was to be able to give the customer the possibility to set up Status/names where each direction of every Flap leads to:


**Inside** <-------- Exit Flap 1 | Entrance Flap 1 ---------> **Gateroom** <--------- Entrance Flap 2 | Exit Flap 2 --------> **Outside**

They told me that is not an option and there is no chance this will happen in the near future.  Would have been to easy ;)

For me a script in Iobroker does the job quite good (Think the caching issues are already fixed because history updates in around 10 seconds):  Trigger, as Sebastian already mentioned, is movement type sureflap.0.*yourhousehold*.history.0.movements.0.type or sureflap.0.*yourhousehold*.history.0.movements.0.updated_at and in combination with the tag id and direction datapoint i fill my own datapoints for each cat in our household.
 
at the time now i just did the script for history.0. and i haven't got the chance to research if the information are reliable if two or three cats go throught the flaps in short time. If the history is updated and there were two cats going through two gates really quick i dont think History.0. would update four times our more. Maybe i'm wrong.

Thanks again for the great job at the adapter and the maintenance. It would be really nice to have a historydatapoint for each cat with movement direction and flap they used. So if some else got the Situations like we do, don't have to spend hours building individual scripts. 
until then if someone (using iobroker) having the same config or planing to use the flaps like we do at the moment and don't know how to work around pls hit me up - maybe i can support with my script.

Cheers
MedusA

**Comment by Sickboy78** [comment]
Hi, feature is implemented in the latest version 2.0.1.

**Comment by MAR-L3Y** [comment]
Hey Sebastian,

first of all good work as always -  thanks for implementing this feature.

my first question is: does the folderstructure and datapoints  stay in case of a value update?
My actual script for the recognition of which cat is where gives me tons of warnings because the orderstructure and datapoints get rebuild with every update of the values and sometimes the script is missing the path cause its not fully built at the time the script triggers.

-Second: are these datapoints also updated  if you set the cat location in the app or over the datapoints or is it just the true movement of the cats

The next Lines i think its just wishes for my specified usecase (if its not possible to implement or take alot of time and work it is good as it is)

It would be awesome to have a folder with datapoints for movement and flap of unknown animals. (direction, time and the flap)
two of our three cats are too fast for the recognition of the surepet pet door (if they move from inside to outside) so they always shown as unknow animals that left a specific flap. Because of my dual pet door setup with a room in between it's possible to recognize the cat entering because both entrances to the room requires unlocking the flap. with this information i track the unknown animal movements and check which cat entered the room last so i can set the location correctly.      
With the build script i track the last 5 entrys of the history and with our three cats the script is around 2800 blocks for just checking this 5 entrys(iobroker is  close to a crash if i unfold all of them ;-) )

I think the type is 13 and the tag_id is 0 for unknown animals 

the second wish is not so important - it would be nice to have the id of the flap as a datapoint too 

as said before thanks again for this great work and all the time you put in that project.
Hope you have a great weekend.
as i ask before -  if its possible to support you with a donation let me know -  Otherwise i'll donate the to my local shelter again.

Cheers
MedusA

**Comment by Sickboy78** [comment]
Hi MedusA,

> does the folderstructure and datapoints stay in case of a value update?

Yes. Recreation of the datapoints was only necessary for the history, as the events had a different structure and different data points depending on the device from which the event originated. E.g. an event from a flap contains movement while an event from a feeder contains weights. But the new movement structure and datapoints stay the same, only the values change.
If you are listening to a value change, I would recommend a delay of some ms. I set all 3 last_* values together, but I cannot guarantee that iobroker will update them at once or in the same order.

> are these datapoints also updated if you set the cat location in the app or over the datapoints or is it just the true movement of the cats

No. Only true movements through the flap are used for these datapoints. If you let your cat otherwise in or out and update the location via app or the adapter, you need to consider the pet.inside datapoint. If the pet.since date is newer then the pet.movement.last_time date, then the location was updated via app or adapter and pet.inside is the correct location. If the pet.movement.last_time date is newer or same as the pet.since date, then you need to calculate the location from last_flap and last_direction. I hope I got this right and there is no logical error in my train of thoughts. ;)

> It would be awesome to have a folder with datapoints for movement and flap of unknown animals

I put it on my todo list.

> it would be nice to have the id of the flap as a datapoint too

Thats easy, will probaly do it soon.

Best regards
